-- ============================================================
-- Microservice Database Initialization
-- ============================================================
--
-- Architecture note:
--   MySQL  → "schema" = database (full isolation between services)
--   PostgreSQL → "schema" = logical namespace inside a database
--                            (NOT the same isolation as MySQL schema)
--
-- For true per-service isolation in PostgreSQL, each microservice
-- gets its OWN DATABASE — not just its own schema.
--
-- This script creates:
--   product_db  — owned exclusively by product_service
--   order_db    — owned exclusively by order_service
--
-- ID columns use VARCHAR(36) to store UUID strings.
-- UUIDs are generated by the application (@PrePersist), not the DB.
-- Cross-service references are plain VARCHAR(36) columns with NO FK.
-- ============================================================


-- ─────────────────────────────────────────────
-- Create the two microservice databases
-- ─────────────────────────────────────────────
CREATE DATABASE product_db;
CREATE DATABASE order_db;


-- ─────────────────────────────────────────────
-- product_db — product_service tables
-- ─────────────────────────────────────────────
\connect product_db

CREATE TABLE IF NOT EXISTS categories (
    id          VARCHAR(36)  NOT NULL,
    name        VARCHAR(255),
    slug        VARCHAR(255),
    is_active   BOOLEAN,
    parent_id   VARCHAR(36),
    created_at  TIMESTAMPTZ,
    updated_at  TIMESTAMPTZ,
    deleted_at  TIMESTAMPTZ,
    created_by  VARCHAR(255),
    updated_by  VARCHAR(255),
    CONSTRAINT pk_categories PRIMARY KEY (id),
    CONSTRAINT fk_categories_parent FOREIGN KEY (parent_id)
        REFERENCES categories (id)
);

CREATE TABLE IF NOT EXISTS products (
    id                  VARCHAR(36)    NOT NULL,
    name                VARCHAR(255),
    slug                VARCHAR(255),
    description         TEXT,
    -- Current selling price: what the customer pays right now.
    -- This value can change at any time (promotions, repricing).
    price               NUMERIC(15, 2),
    -- Original/regular price shown crossed-out in the UI ("Was ₫1,200,000").
    -- NULL means the product is not on sale.
    compare_at_price    NUMERIC(15, 2),
    stock_quantity      INTEGER,
    status              VARCHAR(20),
    created_at          TIMESTAMPTZ,
    updated_at          TIMESTAMPTZ,
    deleted_at          TIMESTAMPTZ,
    created_by          VARCHAR(255),
    updated_by          VARCHAR(255),
    CONSTRAINT pk_products PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS product_categories (
    product_id  VARCHAR(36) NOT NULL,
    category_id VARCHAR(36) NOT NULL,
    CONSTRAINT pk_product_categories PRIMARY KEY (product_id, category_id),
    CONSTRAINT fk_pc_product  FOREIGN KEY (product_id)  REFERENCES products (id),
    CONSTRAINT fk_pc_category FOREIGN KEY (category_id) REFERENCES categories (id)
);


-- ─────────────────────────────────────────────
-- order_db — order_service tables
--
-- Snapshot pattern: order_items stores a copy of the product's
-- name and price AT THE TIME the order was placed.
-- product_id is kept for traceability but has NO foreign key
-- to product_db (services never share database constraints).
-- ─────────────────────────────────────────────
\connect order_db

CREATE TABLE IF NOT EXISTS orders (
    id             VARCHAR(36)    NOT NULL,
    customer_id    VARCHAR(36)    NOT NULL,
    status         VARCHAR(20)    NOT NULL DEFAULT 'PENDING',
    -- Sum of all order_items.subtotal. Represents what the customer owes.
    total_amount   NUMERIC(15, 2) NOT NULL,
    created_at     TIMESTAMPTZ,
    updated_at     TIMESTAMPTZ,
    deleted_at     TIMESTAMPTZ,
    created_by     VARCHAR(255),
    updated_by     VARCHAR(255),
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS order_items (
    id              VARCHAR(36)    NOT NULL,
    order_id        VARCHAR(36)    NOT NULL,
    -- Snapshot fields: copied from product_service at the moment of purchase.
    -- These values never change even if the product is later updated or deleted.
    product_id      VARCHAR(36)    NOT NULL,  -- kept for traceability; no FK to product_db
    product_name    VARCHAR(255)   NOT NULL,  -- snapshot of products.name
    -- Snapshot of products.price at purchase time.
    -- This is the price the customer actually paid per unit.
    unit_price      NUMERIC(15, 2) NOT NULL,
    quantity        INTEGER        NOT NULL,
    -- unit_price * quantity, pre-computed and stored.
    subtotal        NUMERIC(15, 2) NOT NULL,
    created_at      TIMESTAMPTZ,
    updated_at      TIMESTAMPTZ,
    CONSTRAINT pk_order_items PRIMARY KEY (id),
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders (id)
);
